server:
  port: 8081

spring:
  application:
    name: faceMenuManage-user-api

  datasource:
    url: jdbc:mysql://localhost:3306/face_menu_manage?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 871502794
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  redis:
    host: localhost
    port: 6379
    password: 
    database: 1
    timeout: 10000ms

logging:
  level:
    com.facemenu: debug

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html